@startuml

actor Administrador
actor Cliente
actor Contador

rectangle "Sistema Contabilidade Ágil" {

  (Gerenciar sistema) as GS
  (Gerenciar usuários) as GU

  (Enviar documentos) as ED

  (Gerenciar clientes) as GC

  (Revisar lançamentos) as RL
  (Aprovar lançamentos) as AL
  (Corrigir lançamentos) as CL

  (Gerenciar documentos) as GD

  GS -down-> GU : <<include>>

  RL -down-> AL : <<extend>>
  RL -down-> CL : <<extend>>
}

Administrador --> GS

Cliente --> ED

Contador --> ED
Contador --> GC
Contador --> RL
Contador --> GD

@enduml
