@startuml
left to right direction

actor Cliente
actor Contador
actor IA

rectangle "Sistema Contabilidade Ágil" {

  Cliente -- (Enviar Arquivos)

  Contador --> (Gerenciar clientes)
  Contador -- (Gerenciar documentos)
  Contador --> (Revisar lançamentos)

  IA --> (Realizar lançamentos contábeis)

  (Revisar lançamentos) .> (Aprovar lançamentos) : <<extend>>
  (Revisar lançamentos) .> (Corrigir lançamentos) : <<extend>>

  (Realizar lançamentos contábeis) .> (Revisar lançamentos) : <<include>>
}

@enduml
