@startuml
left to right direction

actor Cliente
actor Contador
actor IA

rectangle "Sistema Contabilidade Ágil" {

  (Enviar arquivos) as upload
  (Gerenciar documentos) as documents
  (Gerenciar clientes) as clients
  (Realizar lançamentos contábeis) as cont
  (Revisar lançamentos) as review
  (Aprovar lançamentos) as approve
  (Corrigir lançamentos) as rectify

  Cliente --> upload

  Contador --> upload
  Contador --> cont
  Contador --> review
  Contador -- clients
  Contador -- documents

  IA --> cont

  review .> approve : <<extend>>
  review .> rectify : <<extend>>

  cont .> review : <<include>>
}

@enduml
